export const category = {
  story: [
    "story",
    "tale",
    "novella",
    "narrative",
    "yarn",
    "short story",
    "history",
    "novelette",
  ],
  gameplay: [
    "mission",
    "mechanics",
    "gameplay",
    "quest",
    "game controller",
    "computer game",
    " multiuser",
    " role-playing game",
    " strategy game",
    " arcade",
    " joypad",
    " amusement arcade",
    " video arcade",
    " mouse potato",
    " pinball",
    " adventure game",
    " console",
    " arcade game",
    " games console",
    " joystick",
    " gamer",
    " gamepad",
  ],
  graphic: [
    "visuals",
    "graphic",
    "view",
    "concrete",
    "stirring",
    "striking",
    "telling",
    "colorful",
    "compelling",
    "comprehensible",
    "convincing",
    "definite",
    "descriptive",
    "detailed",
    "distinct",
    "eloquent",
    "expressive",
    "figurative",
    "forcible",
    "illustrative",
    "incisive",
    "intelligible",
    "lively",
    "lucid",
    "moving",
    "perspicuous",
    "picturesque",
  ],
};
